#! /bin/sh

sxhkd &

xrdb ~/.Xresources

FOREGROUND=$(xrdb -query | grep 'foreground:' | awk '{print $NF}')
BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
bspc config top_padding 30
xsetroot -cursor_name left_ptr
bspc monitor -d 'I' 'II' 'III' 'IV' 'V'
bspc config focus_follows_pointer true
bspc config border_width 2
bspc config focused_border_color "$BLUE"
bspc config normal_border_color "$BLACK"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false

feh --bg-fill ~/Pictures/flare.jpg &
bspc rule -a Plasma state=floating manage=off layer=normal
bspc rule -a plasmashell sticky=on layer=above state=floating
killall polybar
polybar top -c ~/.config/polybar/config.ini &
